DROP DATABASE MARKETANDSELLS;
CREATE DATABASE MARKETANDSELLS;

USE MARKETANDSELLS;

CREATE TABLE Products (
    p_id INT PRIMARY KEY AUTO_INCREMENT,
    p_name VARCHAR(50) NOT NULL,
    p_desc TINYTEXT NOT NULL,
    p_price INT DEFAULT 0,
    p_category VARCHAR(25),
    p_img VARCHAR(50)

);
CREATE TABLE Address (
    a_id INT PRIMARY KEY AUTO_INCREMENT,
    a_full VARCHAR(255) NOT NULL,
    a_location TINYTEXT NOT NULL,
    a_contact VARCHAR(12),
    a_email VARCHAR(70)
);
-- PRODUCTS(- CATEGORIES)